### ISSUE TITLE
Preview Time showing the wrong Date

### ISSUE THREAD

**Issue by Vikijaka** [Nightkingale/Wii-U-Time-Sync#1]
While showing the correct time, the date is one month behind, even after multiple restarts

e.g.
WiiU Settings -> June 17th 2023 12:56
WiiU Time Sync Preview Time -> 2023-05-17 12:56:20:0090:0002

EU/ger WiiU 5.5.1e latest aroma
Syncing Enabled: true
Daylight Savings: true
Time Offset (hours): 1
Time Offset (minutes): 0

thank you

**Comment by Nightkingale** [comment]
Thank you for bringing this to my attention! I apologize for the oversight on my part, as I missed this issue during my testing. I now understand that the month is zero-based indexed, meaning that January has a value of `0`, February has a value of `1`, onward.

To address this problem, I will commit a change that increments the value of `ct.tm_mon` once. This adjustment should resolve the issue and display the correct month.
