### ISSUE TITLE
Roundtrip calculation.

### ISSUE THREAD

**Issue by dkosmari** [Nightkingale/Wii-U-Time-Sync#15]
I made a fork to take roundtrip calculation into account, as described in the NTP RFC.

https://github.com/dkosmari/Wii-U-Time-Sync/blob/3575befd6b8543ad5d79187fbb68de92a596eac2/source/main.cpp#L427-L432

```cpp
    ntp_timestamp roundtrip = (t4 - t1) - (t3 - t2);

    double delay = ntp_to_double(roundtrip) / 2;

    // The correct time (t4 + correction) should be t3 + delay.
    double correction = ntp_to_double(t3) + delay - ntp_to_double(t4);
```

I also changed the NTP code to only return the calculated correction, without changing the clock. This allowed me to make further changes to the code, so it can query multiple NTP servers, collect all offsets, and average them out, before modifying the clock.

I ended up making cosmetic changes everywhere, so it's probably not useful as a pull request. But it should be straightforward to borrow the relevant code (roundtrip calculation, storing the correction offset to apply it later) if you're willing to do some refactoring.

**Comment by Nightkingale** [comment]
Hello, and wow, thank you so much! This seems really useful!

Querying multiple servers (in the event the default one can't be connected to) sounds like a cool idea. In fact, your fork has a bunch of quality-of-life improvements that I have still yet to get to! lol

That being said, I'm totally down to bring roundtrip calculations into the main repository (and honestly, most of your other changes, if you wanted to bring them over). I'll sit down tonight, if not sometime this week and try moving the relevant code in.

**Comment by dkosmari** [comment]
While I do think my coding style is better than everyone else's (just kidding, I mostly follow the C++ Core Guidelines), I am aware that it needlessly adds conflicts with the existing pull requests. So I'll leave that decision up to you.

**Comment by Nightkingale** [comment]
I should take notes about your coding style, it's very clean! 😀

For right now, I'll look into adding your implementation of roundtrip calculations as is.

That being said, feel free to submit whatever pull requests you see fit! I really appreciate your fork, so thank you for such awesome improvements! Don't worry too much about conflicts with other open ones, we can absolutely handle them as they become ready for reviewing and merging.

**Comment by Nightkingale** [comment]
I have begun working on my own implementation of roundtrip calculations, which I have pushed as of commit 23e9019. It will likely need more work and testing, but I expect this to be completed and included in the next release, whenever a future release is worth making. If you would like to pull request your own implementation, and the rest of your refactor, feel free to! Thank you again for your work!

**Comment by dkosmari** [comment]
I'm changing the name resolution a bit, to avoid `gethostbyname()`, as it's not thread-safe on the Wii U. I see V10lator already uses `getaddrinfo()` in his fork, I'll be doing the same, to avoid serializing it with a mutex. I want to perform the NTP queries in parallel. I'll submit a PR after this is done.

**Comment by Nightkingale** [comment]
Sounds great, thank you very much!
